// /home/Coder/prueba-nodejs/api-riwimedicare/src/modules/user/user.model.ts

import { DataTypes, Model, Optional } from "sequelize";
import { sequelize } from "../../core/database/database";

/**
 * 1. Total Attributes Interface
 */
export interface UserAttributes {
    id: string;
    email: string;
    passwordHash: string;
    roleId: string;
    createdAt?: Date;
    updatedAt?: Date;
}

/**
 * 2. Record Creation Interface
 * ‘id’ is auto-generated by PostgreSQL, so it is optional when instantiating.
 */
export interface UserCreationAttributes extends Optional<UserAttributes, "id"> {}

/**
 * 3. Model Class Declaration
 */
export class User extends Model<UserAttributes, UserCreationAttributes> implements UserAttributes {
    declare public id: string;
    declare public email: string;
    declare public passwordHash: string;
    declare public roleId: string;

    declare public readonly createdAt: Date;
    declare public readonly updatedAt: Date;

    /**
     * Overrides the native serialization method. Express calls this implicitly
     * when executing `res.json(user)`. Ensures that the password hash is never sent over the network.
     */
    public toJSON(): object {
        const attributes = { ...this.get() };

        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        delete attributes.passwordHash;

        return attributes;
    }
}

/**
 * 4. Initialization of the Model and Physical Schema
 */
User.init(
    {
        id: {
            type: DataTypes.UUID,
            defaultValue: DataTypes.UUIDV4,
            primaryKey: true,
        },
        email: {
            type: DataTypes.STRING(150),
            allowNull: false,
            unique: true,
            validate: {
                isEmail: {
                    msg: "The email address provided is invalid.",
                },
            },
        },
        passwordHash: {
            type: DataTypes.STRING(255),
            allowNull: false,
        },
        roleId: {
            type: DataTypes.UUID,
            allowNull: false,
        },
    },
    {
        sequelize,
        tableName: "users",
        timestamps: true,
        underscored: true,

        indexes: [{ unique: true, fields: ["email"] }],
    },
);

export default User;
